inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

Rails:
  Enabled: false

# {} は 1 行で書くときに主に使われるので、スペースよりも
# 横に長くならない方が嬉しさが多い。
# そもそも {| のスタイルの方が一般的だったと認識している。
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

# 2行以上の空行を許可する
Layout/EmptyLines:
  Enabled: false

# 行の長さの最大値を110に
Metrics/LineLength:
  Max: 110
